name: Check code updates
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  linter:
    name: Check code style (Ruby 3.0.2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install rubocop
        run: gem install rubocop --no-doc

      - name: Run linter
        run: bundle exec rubocop

  tests:
    name: Run tests (Ruby ${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.0.0 # msrv
          - 3.0.2
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
